image: python:3.9

before_script:
  - pip install -r requirements.txt

auto_format:
  stage: build
  script:
    - nox -s ${{ NOXSESSION }}
  parallel:
    matrix:
      - NOXSESSION: ["fmt", "autolint"]

quality:
  stage: test
  script:
    - nox -s ${{ NOXSESSION }}
  parallel:
    matrix:
      - NOXSESSION: [ "fmt_check", "lint", "type_check", "docs" ]

# test-docs:
#   stage: test
#   script:
#   - mkdocs build --strict --verbose --site-dir test
#   artifacts:
#     paths:
#     - test
#   rules:
#     - if: $CI_COMMIT_REF_NAME != $CI_DEFAULT_BRANCH

pages:
  stage: deploy
  script:
  - mkdocs build --strict --verbose
  - mv site public  
  artifacts:
    paths:
    - public
  only:
  - master

# deploy-prod:
#   stage: deploy
#   script:
#     - echo "This job deploys something from the $CI_COMMIT_BRANCH branch."
